/*
 * This source file was generated by the Gradle 'init' task
 */
package com.jrxna.mongoose;

import org.junit.jupiter.api.Test;
// import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        // Tests to be written
    }
}
